INSERT INTO RESTAURANT (restaurantName, phone, location, imageurl) VALUES
('Pizza Kottaram', '123-456-7890', 'Vellayambalom', '/static/images/cheesyPizza.jpg'),
('Sushi Kada', '987-654-3210', 'Kowdiar', '/static/images/SalmonNigiri (1).jpg'),
('Njetikkal Mandhi Kada', '555-555-5555', 'Poojapura', '/static/images/kuzhiMandi (1).jpg'),
('Howweda Chayakada', '555-555-5555', 'Palayam', '/static/images/Chayakada.jpeg'),
('Ikkakkante Sarbath', '555-555-5555', 'Pattom', '/static/images/LemonSarbath.jpg'),
('Matcha Kudicha?', '555-555-5555', 'Kuravankonam', '/static/images/matcha_kudicho.jpeg'),
('Vedikkett Burger', '555-555-5555', 'Peyad', '/static/images/ClassicCheeseBurger.jpg'),
('Porotta Adich Keri Vaaa', '555-555-5555', 'Karamana', '/static/images/BunPorotta (1).jpg'),
('Theeppori Birnani', '555-555-5555', 'Thiruvananthapuram', '/static/images/ChickenBiriyani (1).jpg');


INSERT INTO MENU_ITEMS (restaurantId, itemName, description, isVeg, cuisineType, price, imageurl) VALUES
(1, 'Hawaiian Pizza', 'Pizza with ham and pineapple', FALSE, 'Italian', 11.99, '/static/images/HawaiianPizza (1).jpg'),
(1, 'Veggie Pizza', 'Pizza with assorted vegetables', TRUE, 'Italian', 9.99, '/static/images/vegPizza.jpg'),
(1, 'BBQ Chicken Pizza', 'Pizza with BBQ chicken and onions', FALSE, 'Italian', 12.99, '/static/images/bbqPizza (1).jpg'),
(1, 'Four Cheese Pizza', 'Pizza with four types of cheese', TRUE, 'Italian', 10.99, '/static/images/cheesyPizza.jpg'),
(1, 'Meat Lovers Pizza', 'Pizza loaded with various meats', FALSE, 'Italian', 13.99, '/static/images/meatLoversPizza (1).jpg'),
(2, 'Salmon Nigiri', 'Fresh salmon over rice', FALSE, 'Japanese', 7.99, '/static/images/SalmonNigiri (1).jpg'),
(2, 'Tuna Sashimi', 'Fresh tuna slices', FALSE, 'Japanese', 8.99, '/static/images/TunaSashimi.jpg'),
(2, 'Vegetable Sushi Roll', 'Roll with mixed vegetables', TRUE, 'Japanese', 5.99, '/static/images/VegSushiRoll (1).jpg'),
(2, 'Shrimp Tempura Roll', 'Roll with shrimp tempura', FALSE, 'Japanese', 9.99, '/static/images/ShrimpTempuraRoll (1).jpg'),
(2, 'Spicy Tuna Roll', 'Roll with spicy tuna', FALSE, 'Japanese', 8.99, '/static/images/SpicyTuna (1).jpg'),
(3, 'Beef Mandhi', 'Spiced beef cooked with rice', FALSE, 'Indian', 10.99, '/static/images/beefMandi (1).jpg'),
(3, 'Fish Mandhi', 'Spiced fish cooked with rice', FALSE, 'Indian', 11.99, '/static/images/HoneyChilliMandi (1).jpg'),
(3, 'Mutton Mandhi', 'Spiced mutton cooked with rice', FALSE, 'Indian', 12.99, '/static/images/muttonMandi (1).jpg'),
(3, 'Prawn Mandhi', 'Spiced prawns cooked with rice', FALSE, 'Indian', 13.99, '/static/images/periperiMandi.jpg'),
(3, 'Egg Mandhi', 'Spiced eggs cooked with rice', FALSE, 'Indian', 9.99, '/static/images/kuzhiMandi (1).jpg'),
(4, 'Masala Chai', 'Spiced tea with milk', TRUE, 'Indian', 2.99, '/static/images/masalaChai.jpg'),
(4, 'Green Tea', 'Plain green tea', TRUE, 'Chinese', 2.49, '/static/images/greentea (1).jpg'),
(4, 'Black Tea', 'Plain black tea', TRUE, 'British', 2.49, '/static/images/blackTea.jpg'),
(4, 'Lemon Tea', 'Tea with lemon', TRUE, 'Indian', 2.99, '/static/images/lemonTea (1).jpg'),
(4, 'Ginger Tea', 'Tea with ginger', TRUE, 'Indian', 2.99, '/static/images/GingerTea (1).jpg'),
(5, 'Rose Sarbath', 'Sweet rose flavored drink', TRUE, 'Indian', 3.99, '/static/images/RoseSarbath (1).jpg'),
(5, 'Lemon Sarbath', 'Tangy lemon drink', TRUE, 'Indian', 3.49, '/static/images/LemonSarbath.jpg'),
(5, 'Mango Sarbath', 'Sweet mango drink', TRUE, 'Indian', 4.49, '/static/images/MangoSarbath (1).jpg'),
(5, 'Pineapple Sarbath', 'Pineapple flavored drink', TRUE, 'Indian', 4.49, '/static/images/PineappleSarbath (1).jpg'),
(5, 'Orange Sarbath', 'Orange flavored drink', TRUE, 'Indian', 3.99, '/static/images/OrangeSarbath (1).jpg'),
(6, 'Matcha Latte', 'Matcha powder with milk', TRUE, 'Japanese', 4.99, '/static/images/MatchaLatte.jpg'),
(6, 'Iced Matcha', 'Cold matcha drink', TRUE, 'Japanese', 4.49, '/static/images/IcedMatcha.jpg'),
(6, 'Matcha Smoothie', 'Matcha blended with fruits', TRUE, 'Japanese', 5.99, '/static/images/MatchaSmoothie.jpg'),
(6, 'Matcha Tea', 'Traditional matcha tea', TRUE, 'Japanese', 3.99, '/static/images/MatchaTea (1).jpg'),
(6, 'Matcha Ice Cream', 'Matcha flavored ice cream', TRUE, 'Japanese', 4.99, '/static/images/MatchaIcecream (1).jpg'),
(7, 'Cheese Burger', 'Burger with cheese', FALSE, 'American', 7.99, '/static/images/ClassicCheeseBurger.jpg'),
(7, 'Veggie Burger', 'Burger with vegetables', TRUE, 'American', 6.99, '/static/images/VeggieBurger.jpg'),
(7, 'Chicken Burger', 'Burger with chicken', FALSE, 'American', 8.99, '/static/images/StuffedChickenBurger (1).jpg'),
(7, 'Bacon Burger', 'Burger with bacon', FALSE, 'American', 9.99, '/static/images/BaconBurger (1).jpg'),
(7, 'Double Patty Burger', 'Burger with two patties', FALSE, 'American', 10.99, '/static/images/DoublePattyBurger (1).jpg'),
(8, 'Chicken Porotta', 'Porotta with chicken curry', FALSE, 'Indian', 6.99, '/static/images/ChickenPorotta (1).jpg'),
(8, 'Beef Porotta', 'Porotta with beef curry', FALSE, 'Indian', 7.99, '/static/images/BeefPorotta (1).jpg'),
(8, 'Coin Porotta', 'Porotta', TRUE, 'Indian', 5.99, '/static/images/CoinPorotta (1).jpg'),
(8, 'Bun Porotta', 'Porotta', FALSE, 'Indian', 6.49, '/static/images/BunPorotta (1).jpg'),
(8, 'Mutton Porotta', 'Porotta with mutton curry', FALSE, 'Indian', 8.99, '/static/images/MuttonPorotta (1).jpg'),
(9, 'Veg Biriyani', 'Long grain basmati rice layered with mixed vegetables', TRUE, 'Indian', 9.99, '/static/images/VegBiriyani (1).jpg'),
(9, 'Chicken Biriyani', 'Tender marinated chicken layered with long grain basmati rice', FALSE, 'Indian', 12.99, '/static/images/ChickenBiriyani (1).jpg'),
(9, 'Thalassery Dum Biriyani', ' South Indian style biriyani', TRUE, 'Indian', 10.99, '/static/images/ThalasseriDumBiriyani (1).jpg'),
(9, 'Malabar Biriyani', 'North Indian style biriyani', FALSE, 'Indian', 11.99, '/static/images/DindigulThalapakatiBiriyani (1).jpg'),
(9, 'Rajasthani Biriyani', 'Rajasthani style biriyani', TRUE, 'Indian', 13.99, '/static/images/AasifeBiriyani (1).jpg');